Repository RYGhub/impressive-strawberry, pull requests merged in 2021-11, with the labels that each got.

#1 Improve models quality before creating the first migration
  .idea/inspectionProfiles/Project_Default.xml
  impressive_strawberry/database/tables.py
  impressive_strawberry/web/models.py
Labels: feature

#2 Improve docs, add examples and specify encoders in models
  impressive_strawberry/database/tables.py
  impressive_strawberry/web/models.py
Labels: bug, docs, feature

#5 💥 Complete file structure refactor
  .idea/misc.xml
  impressive_strawberry/database/alembic/versions/713b76b25d40_first_revision.py
  impressive_strawberry/database/engine.py
  impressive_strawberry/database/tables.py
  impressive_strawberry/web/app.py
  impressive_strawberry/web/auth/deps.py
  impressive_strawberry/web/crud/__init__.py
  impressive_strawberry/web/deps/__init__.py
  impressive_strawberry/web/deps/auth.py
  impressive_strawberry/web/deps/database.py
  impressive_strawberry/web/description.md
  impressive_strawberry/web/errors/__init__.py
  impressive_strawberry/web/handlers/__init__.py
  impressive_strawberry/web/models.py
  impressive_strawberry/web/models/__init__.py
  impressive_strawberry/web/models/base.py
  impressive_strawberry/web/models/edit.py
  impressive_strawberry/web/models/error.py
  impressive_strawberry/web/models/full.py
  impressive_strawberry/web/models/read.py
  impressive_strawberry/web/response_schema.py
  impressive_strawberry/web/responses/__init__.py
  impressive_strawberry/web/responses/raw.py
  impressive_strawberry/web/routes/api/application/v1/router.py
  poetry.lock
  pyproject.toml
Labels: feature

#6 Add groups endpoints
  .idea/runConfigurations/impressive_strawberry_web.xml
  impressive_strawberry/web/__main__.py
  impressive_strawberry/web/app.py
  impressive_strawberry/web/crud/__init__.py
  impressive_strawberry/web/models/edit.py
  impressive_strawberry/web/models/read.py
  impressive_strawberry/web/routes/api/group/v1/router.py
Labels: feature

#7 ✨ Add group and achievement routes
  impressive_strawberry/database/alembic/versions/f2eff2e29545_add_achievement_crystal.py
  impressive_strawberry/database/tables.py
  impressive_strawberry/web/app.py
  impressive_strawberry/web/deps/__init__.py
  impressive_strawberry/web/deps/achievement.py
  impressive_strawberry/web/deps/application.py
  impressive_strawberry/web/deps/group.py
  impressive_strawberry/web/models/base.py
  impressive_strawberry/web/models/edit.py
  impressive_strawberry/web/models/read.py
  impressive_strawberry/web/routes/api/achievements/v1/router.py
  impressive_strawberry/web/routes/api/group/v1/router.py
Labels: feature

#8 ✨ Add user routes
  impressive_strawberry/database/tables.py
  impressive_strawberry/web/app.py
  impressive_strawberry/web/deps/__init__.py
  impressive_strawberry/web/deps/user.py
  impressive_strawberry/web/models/edit.py
  impressive_strawberry/web/models/full.py
  impressive_strawberry/web/models/read.py
  impressive_strawberry/web/routes/api/user/v1/router.py
Labels: feature

#11 ✨ Create testing framework
  .gitignore
  .idea/runConfigurations/pytest_in_impressive_strawberry.xml
  impressive_strawberry/web/testing/conftest.py
  impressive_strawberry/web/testing/test_application.py
  poetry.lock
  pyproject.toml
  strawberry.iml
Labels: feature

#12 🐛 Creations should always return 201
  impressive_strawberry/web/routes/api/achievements/v1/router.py
  impressive_strawberry/web/routes/api/application/v1/router.py
  impressive_strawberry/web/routes/api/group/v1/router.py
  impressive_strawberry/web/routes/api/user/v1/router.py
Labels: bug

#19 🔨 Fix Poetry environment
  poetry.lock
  strawberry.iml
Labels: dependencies

#9 ✨ Add unlocks routes
  impressive_strawberry/web/app.py
  impressive_strawberry/web/deps/__init__.py
  impressive_strawberry/web/deps/achievement.py
  impressive_strawberry/web/deps/unlock.py
  impressive_strawberry/web/deps/user.py
  impressive_strawberry/web/errors/__init__.py
  impressive_strawberry/web/models/full.py
  impressive_strawberry/web/routes/api/achievement/v1/router.py
  impressive_strawberry/web/routes/api/unlock/v1/router.py
  poetry.lock
  strawberry.iml
Labels: feature

#20 🧪 Test `application` routes
  impressive_strawberry/web/testing/test_application.py
Labels: automation
